# Generated by Django 3.1.2 on 2020-10-24 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_auto_20201024_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstats',
            name='current_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='performance.team'),
        ),
    ]
