# Generated by Django 3.1.2 on 2020-10-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_auto_20201024_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstats',
            name='bowl_average',
            field=models.FloatField(),
        ),
    ]
