# Generated by Django 3.1.2 on 2020-10-25 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0004_auto_20201025_0757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerstats',
            old_name='bowl_stike_rate',
            new_name='bowl_strike_rate',
        ),
    ]
